export const disciplines = {
  "Artes": [],
  "Biologia": [],
  "Educação física": [],
  "Filosofia": [],
  "Física": [],
  "Geografia": [],
  "História": [],
  "Língua estrangeira (Espanhol/Inglês)": [],
  "Língua portuguesa": [
    "Compreensão e Interpretação de texto",
    "Técnicas de leitura",
    "Estrutura e formação de palavras",
    "Funções da linguagem",
    "Elementos da Comunicação",
    "Gêneros textuais",
    "Tipologia textual",
    "Intertextualidade e Paráfrase",
    "Figuras de linguagem",
    "Efeitos de Sentido",
    "Semântica",
    "Linguagem, Língua e Fala",
    "Variação Linguística",
    "Conjunção e Palavras denotativas: Conceito, classificações e aplicações",
    "Vocabulário aplicado à prova"
  ],
  "Literatura": [
    "Introdução à Literatura",
    "Gêneros literários: Épico, lírico, dramática, ensaístico",
    "Elementos da poesia",
    "Elementos da prosa",
    "Trovadorismo",
    "Humanismo",
    "Classicismo",
    "Quinhentismo",
    "Barroco: origem, contexto histórico e características",
    "Barroco: Gregório de Matos Guerra e Pe. Antônio Vieira",
    "Arcadismo: origem, contexto histórico e características",
    "Arcadismo: Tomás Antônio Gonzaga e Cláudio Manuel da Costa",
    "Romantismo: origem, contexto histórico e características",
    "1a Geração Romântica",
    "2a Geração Romântica",
    "3a Geração Romântica",
    "José de Alencar e Manuel Antônio de Almeida",
    "Realismo",
    "Eça de Queirós e Machado de Assis",
    "Naturalismo",
    "Parnasianismo",
    "Simbolismo",
    "Pré-Modernismo",
    "Euclides da Cunha e Lima Barreto",
    "Monteiro Lobato e Augusto dos Anjos",
    "Vanguardas Europeias",
    "Fernando Pessoa",
    "Semana de Arte Moderna",
    "1a Fase Modernista",
    "Mário de Andrade, Oswald de Andrade e Manuel Bandeira",
    "2a Fase Modernista",
    "Graciliano Ramos, Carlos Drummond de Andrade e Vinicius de Moraes",
    "3a Fase Modernista",
    "Guimarães Rosa, Clarice Lispector e João Cabral de Melo Neto",
    "Pós-modernismo",
    "Concretismo e Neoconcretismo",
    "Tropicalismo",
    "Poesia Marginal",
    "Poesia-Práxis",
    "Poema processo",
    "Haicai",
    "Autores Contemporâneos",
    "Literatura de cordel",
    "Prosa contemporânea",
    "Análise de Obras"
  ],
  "Matemática": [
    "Adição e Subtração",
    "Multiplicação e Divisão",
    "Notações Matemáticas e Glossário Básico",
    "Operações com Números Reais",
    "Divisibilidade, MMC e MDC",
    "Conjuntos Numéricos",
    "Frações",
    "Propriedades Distributivas",
    "Potenciação",
    "Radiciação",
    "Produtos Notáveis",
    "Fatoração",
    "Sistemas Métricos e Base Decimal",
    "Lógica Matemática",
    "Equação de Primeiro Grau",
    "Equação de Segundo Grau",
    "Equação Exponencial",
    "Porcentagem",
    "Aumentos e Descontos Percentuais",
    "Juros Simples e Compostos",
    "Razão, Proporção e Escala Cartográfica",
    "Regra de Três Simples e Composta",
    "Interpretação de Gráficos e Tabelas",
    "Estatística: Média, Mediana e Moda",
    "Frequência Absoluta e Relativa",
    "Variância e Desvio Padrão",
    "Introdução a Funções e Domínio de uma função real",
    "Teoria dos Conjuntos",
    "Função Constante e Função Afim",
    "Introdução à Função Quadrática",
    "Função Quadrática: Pontos Extremos",
    "Função Composta e Inversa",
    "Módulo e Função Modular",
    "Função Exponencial",
    "Inequações do Primeiro e Segundo Grau",
    "Inequações: Produto e Quociente",
    "Inequação Exponencial",
    "Logaritmos: Definição e Existência",
    "Logaritmos: Propriedades",
    "Equações Logarítmicas",
    "Funções Logarítmicas",
    "Inequação Logarítmica",
    "Polinômios Fundamentos",
    "Equações Polinomiais",
    "Progressão Aritmética: Definição e Termo Geral",
    "Progressão Aritmética: Soma dos Termos",
    "Progressão Geométrica: Definição e Termo Geral",
    "Progressão Geométrica: Soma dos Termos e da Convergente Infinita",
    "Fatorial",
    "Princípio Fundamental da Contagem",
    "Permutações",
    "Arranjos e Combinações",
    "Números Binomiais",
    "Probabilidade: Definição",
    "Probabilidade: Aplicações práticas",
    "Probabilidade condicional",
    "Matriz: Conceito e Operações Básicas",
    "Matriz: produto",
    "Definição e Cálculo: Determinantes",
    "Método de Escalonamento",
    "Sistemas Lineares: Discussão",
    "Sistema Linear Homogêneo",
    "Noções Primitivas de Geometria Plana",
    "Triângulos",
    "Pontos Notáveis de um Triângulo",
    "Semelhança de Triângulos e Teorema de Tales",
    "Quadriláteros",
    "Polígonos",
    "Triângulo Retângulo",
    "Lei dos Senos e Cossenos",
    "Áreas de Polígonos",
    "Círculos",
    "Ângulos na Circunferência",
    "Poliedros",
    "Prismas",
    "Pirâmides",
    "Cilindros",
    "Cones",
    "Esferas",
    "Troncos",
    "Inscrição de Sólidos",
    "Sistema Cartesiano e Ponto",
    "Estudo Analítico da Reta",
    "Circunferência",
    "Posições Relativas à Circunferência",
    "Cônicas",
    "Trigonometria no Triângulo Retângulo",
    "Arcos e Ciclo Trigonométrico",
    "Função Seno e Cosseno",
    "Função Tangente e Cotangente",
    "Equações e Inequações Trigonométricas"
  ],
  "Redação": [
    "O Texto Dissertativo-argumentativo: Características e Particularidades",
    "O Texto Dissertativo-argumentativo: Estrutura",
    "Concisão no Parágrafo e Progressão Textual",
    "O Tema na Redação do ENEM: Particularidades, Interpretação e Delimitação",
    "Projeto de Texto",
    "Marca de Autoria",
    "Fuga e Tangência",
    "Aspectos Formais Relevantes",
    "Gramática Aplicada à Redação: Concordância verbal e nominal",
    "Gramática Aplicada à Redação: Regência verbal e nominal",
    "Gramática Aplicada à Redação: Acentuação",
    "Gramática Aplicada à Redação: Pontuação",
    "Gramática Aplicada à Redação: Crase",
    "Gramática Aplicada à Redação: Ortografia",
    "Vícios de linguagem: Conceito, Classificação e Tipos",
    "Título",
    "Introdução: Função e Microestrutura",
    "Tese",
    "Desenvolvimento: Função e Estrutura",
    "Métodos de raciocínio: indução e dedução",
    "Métodos de raciocínio: dialética e falhas na argumentação",
    "Argumentação e estratégias argumentativas",
    "Repertório Sociocultural: Conceito, aplicação e classificação",
    "Conclusão: Função e Microestrutura",
    "Proposta de intervenção: Agente",
    "Proposta de intervenção: Ação",
    "Proposta de intervenção: Meio/Modo",
    "Proposta de intervenção: Detalhamento",
    "Proposta de intervenção: Finalidade",
    "Redação ENEM: Competência 1",
    "Redação ENEM: Competência 2",
    "Redação ENEM: Competência 3",
    "Redação ENEM: Competência 4",
    "Redação ENEM: Competência 5",
    "Leitura e aproveitamento da coletânea/ texto de apoio",
    "Coesão Textual: Conceito, Classificação e Tipos",
    "Coerência Textual",
    "Análise de redações Exemplares: 1",
    "Análise de redações Exemplares: 2"
  ],
  "Química": [
    "Propriedades da matéria",
    "Substâncias químicas e suas transformações",
    "Substâncias puras, Misturas homogêneas e Misturas Heterogêneas",
    "Separação de Misturas",
    "Modelos Atômicos: Dalton e Thomson",
    "Modelos Atômicos: Rutherford",
    "Modelos Atômicos: Bohr",
    "Atomística: Composição e Propriedades Atômicas e Interatômicas",
    "Distribuição Eletrônica",
    "Tabela Periódica: Classificação periódica e Propriedades Periódicas",
    "Ligação Iônica",
    "Ligação Covalente e Dativa",
    "Ligação Metálica",
    "Geometria Molecular",
    "Polaridade das ligações químicas",
    "Polaridade das moléculas",
    "Interações Intermoleculares",
    "Princípio da Solubilidade",
    "Massa atômica e Massa molecular",
    "Definição de Mol e Massa molar",
    "Cálculos de Mol",
    "Leis ponderais",
    "Fórmula percentual, mínima e molecular",
    "Balanceamento de equações químicas",
    "Cálculo Estequiométrico: casos simples",
    "Cálculo Estequiométrico: reagente em excesso e limitante",
    "Cálculo Estequiométrico: pureza e rendimento",
    "Soluções e solubilidade: Conceitos e Propriedades",
    "Concentração de soluções 1",
    "Concentração de soluções 2",
    "Diluição de soluções",
    "Mistura de soluções",
    "Titulação",
    "Comportamento físico dos gases",
    "Transformações Isotérmicas, Isobáricas e Isovolumétricas",
    "Equação geral dos gases",
    "Lei de Avogadro",
    "Equação de Clapeyron",
    "Mistura gasosa e Densidade dos gases",
    "Termoquímica: conceitos e Entalpia",
    "Cálculo da variação de Entalpia",
    "Entalpia de combustão e poder calorífico",
    "Lei de Hess",
    "Número de oxidação Nox",
    "Reações de oxirredução",
    "Pilhas",
    "Eletrólise ígnea",
    "Eletrólise Aquosa e galvanização",
    "Eletrólise quantitativa",
    "Tonoscopia, Ebulioscopia, Crioscopia e Osmocopia",
    "Introdução à Química Orgânica e Cadeias Carbônicas",
    "Hidrocarbonetos: nomenclatura e classificação",
    "Cadeias Aromáticas",
    "Funções Orgânicas: Oxigenados",
    "Funções Orgânicas: Nitrogenados e Haletos Orgânicos",
    "Isomeria Plana",
    "Isomeria Geométrica",
    "Isomeria Óptica",
    "Propriedades Físicas dos Compostos Orgânicos",
    "Ácidos e Bases Orgânicos",
    "Reações Orgânicas: Adição",
    "Reações Orgânicas: Substituição",
    "Reações orgânicas: Eliminação e Esterificação",
    "Reações Orgânicas: Oxidação",
    "Bioquímica: lipídeos, proteínas e carboidratos",
    "Polímeros",
    "Petróleo",
    "Radioatividade: definição, conceitos",
    "Emissões radioativas",
    "Decaimento Radioativo, Fusão e Fissão nuclear",
    "Química Ambiental e Poluição Atmosférica",
    "Ácidos: definição, nomenclatura e ionização",
    "Bases: definição, nomenclatura e dissociação",
    "Reações de Neutralização: ácido + base",
    "Sais: Definição, nomenclatura e classificação",
    "Óxidos: Definição, nomenclatura e classificação",
    "Reações Inorgânicas: adição e decomposição",
    "Reações Inorgânicas: simples-troca ou deslocamento",
    "Reações inorgânicas: dupla-troca",
    "Introdução à Cinética Química",
    "Condições de ocorrência das reações - Teoria das colisões e Complexo Ativado",
    "Fatores que influenciam a velocidade da reação química e catalisadores",
    "Equilíbrio Químico: definição e conceitos",
    "Constante de Equilíbrio - Kc",
    "Deslocamento do Equilíbrio Químico",
    "pH",
    "Hidrólise Salina"
  ],
  "Sociologia": [
    "Surgimento da Sociologia: Contexto Histórico-Social",
    "Augusto Comte: Positivismo e a Lei dos Três Estados",
    "Émile Durkheim: Sociologia como Ciência e Fatos Sociais",
    "Émile Durkheim: Instituições Sociais, Solidariedade e Suicídio",
    "Max Weber: Ética Protestante e o Espírito Do Capitalismo",
    "Max Weber: Poder, Dominação Legítima e Ação Social",
    "Etnocentrismo e Antropologia Social",
    "Evolucionismo Cultural e Relativismo Social",
    "Friedrich Hegel: Método Dialético",
    "Karl Marx: Materialismo Histórico, Alienação e Mais-Valia",
    "Karl Marx: Luta de Classes e Manifesto Comunista",
    "Antônio Gramsci: Hegemonia Cultural",
    "Declaração dos Direitos do Homem e do Cidadão, 1789",
    "Declaração Universal dos Direitos Humanos, 1948",
    "Constituição de 1988: Constituição Cidadã, 1988",
    "Marshall: Cidadania e Classe Social",
    "Teoria do Trabalho: Durkheim, Marx e Weber",
    "Novas Relações de Trabalho, Precarização do Trabalho e Escravidão Moderna",
    "Segregação Socioespacial Urbana, Atitude Blasé e Gentrificação",
    "Função Social do Espaço Público e Gestão Participativa",
    "Patrimônio Cultural Material e Imaterial Brasileiro e Bens Culturais",
    "Apropriação Cultural e Ressignificação Cultural",
    "Racismo, Ações Afirmativas e Resistência Cultural",
    "Sérgio Buarque de Holanda: Homem Cordial",
    "Gilberto Freyre e Florestan Fernandes: Relações Raciais no Brasil",
    "Marginalização Social e Carolina Maria de Jesus: Quarto de Despejo",
    "Segregação Racial nos EUA e Apartheid na África do Sul",
    "Desobediência Civil: David Henry Thoreau e Mahatma Gandhi",
    "Desigualdade Social, Estratificação Social e Mobilidade Social",
    "Dominação, Manutenção do Status Quo e o Mito da Meritocracia",
    "Minorias Sociais e Luta Política",
    "Sociedade em Rede, Sociedade Informacional e Mídias Sociais",
    "Opressão contra a Mulher, Luta por Igualdade de Direitos e Movimento Sufragista",
    "Diversidade Cultural, Estereótipos de Gênero e Invisibilidade Social",
    "Identidade Cultural e Globalização",
    "Indústria Cultural: Escola de Frankfurt, Adorno e Horkheimer",
    "Habermas: Teoria da Ação Comunicativa",
    "Cultura de Massa e Sociedade do Espetáculo",
    "Consumismo, Individualismo, Tribalismo, Sujeito Pós-Moderno",
    "Michel Foucault: Poder e Controle Social",
    "Zygmunt Bauman: Modernidade Líquida",
    "Gilles Lipovetsky: Hipermodernidade",
    "Paulo Freire: Pedagogia do Oprimido",
    "Equidade e John Rawls: Teoria da Justiça"
  ],
  "Tecnologia da informação e comunicação": [
    "Função e Impacto das Novas Mídias",
    "Gêneros Digitais",
    "Cibercultura",
    "Redes Sociais e Relações na Sociedade Atual",
    "Metaverso",
    "Meios de Comunicação e a Indústria Cultural",
    "Internet, as Organizações Políticas e a Censura",
    "Marco Civil da Internet",
    "Ética na internet",
    "Privacidade na Internet",
    "Inclusão digital e acesso democrático",
    "Letramento digital",
    "Criptomoedas e Economia digital",
    "Inteligência artificial e internet das coisas",
    "Marketing tradicional x Marketing digital"
  ]
};
