export const disciplines = {
  "Artes": [
    "Arte: conceitos, modalidades, estéticas, funções e estados",
    "Elementos básicos de artes plásticas",
    "Arte Pré-Histórica",
    "Arte Suméria e Cretense",
    "Arte Egípcia",
    "Arte Egeia",
    "Arte Grega",
    "Arte Romana",
    "Arte Cristã",
    "Arte Bizantina",
    "Arte Românica",
    "Arte Gótica",
    "Arte Renascentista",
    "Arte da América Pré-Colombiana",
    "Arte Barroca",
    "Rococó",
    "Arte Neoclássica",
    "Arte Romântica",
    "Realismo",
    "Movimento das Artes e Ofício e Art Nouveau",
    "Impressionismo",
    "Pós-Impressionismo",
    "Expressionismo Alemão",
    "Cubismo",
    "Futurismo",
    "Fauvismo",
    "Surrealismo",
    "Dadaísmo",
    "Pop Arte",
    "Arquitetura e Escultura Moderna",
    "Arte da Sociedade Industrial",
    "Fotografia e fotogramas",
    "Ópera do século XIX",
    "Arte Pré-Histórica Brasileira",
    "Arte Indígena e Africana",
    "Cerâmica marajoara",
    "Arte Barroca no Brasil",
    "Missão Artística Francesa",
    "Academicismo",
    "Arte Moderna Brasileira",
    "Movimento Modernista",
    "Xilogravura nordestina",
    "Arte Contemporânea Brasileira",
    "Body Art",
    "Arte performática",
    "Arte Digital",
    "Hip hop e grafite",
    "Colagem e decollage",
    "Elementos básicos da música",
    "Música no século XX",
    "Teatro brasileiro"
  ],
  "Biologia": [
    "Origem da vida",
    "Teorias Evolucionistas: Lamarck, Darwin e Teoria Sintética",
    "Mecanismos de Especiação e Conceitos da Evolução",
    "Ecologia: Conceitos básicos",
    "Cadeias Alimentares",
    "Pirâmides Ecológicas",
    "Bioacumulação/Magnificação Trófica",
    "Ciclo do Carbono, do Nitrogênio, da Água e do Oxigênio",
    "Sucessão Ecológica",
    "Relações Ecológicas",
    "Dinâmica das populações",
    "Problemas ambientais: poluição atmosférica",
    "Problemas ambientais: poluição da água e do solo",
    "Problemas ambientais: poluição no ambiente urbano",
    "Água, Sais Minerais e Vitaminas",
    "Carboidratos e Lipídeos",
    "Proteínas: estrutura, funções e enzimas",
    "Nucleotídeos e Ácidos nucleicos",
    "Vírus x Célula procariótica x Célula Eucariótica",
    "Organelas Celulares",
    "Membrana Celular e seus constituintes",
    "Difusão e Osmose",
    "Transporte Ativo",
    "Transporte, armazenamento e secreção celular",
    "Digestão celular",
    "Metabolismo Energético: vias metabólicas e ATP",
    "Fermentação e Respiração Anaeróbia",
    "Respiração Aeróbia: Glicólise, Ciclo de Krebs e Fosforilação Oxidativa",
    "Fotossíntese: etapas do processo fotossintético",
    "Fatores limitantes e reguladores da Fotossíntese",
    "Replicação do DNA",
    "Transcrição",
    "Tradução e Código Genético",
    "Núcleo Celular: estruturas do núcleo",
    "Ciclo celular",
    "Mitose: características e fases",
    "Meiose: características e fases",
    "Gametogênese",
    "Genética: Fundamentos da Hereditariedade",
    "Primeira Lei de Mendel",
    "Heredograma e Cruzamento Teste",
    "Herança monogênica, Alelos Múltiplos e Pleiotropia",
    "Codominância, Dominância Incompleta, Genes letais",
    "Sistema ABO e Sistema Rh",
    "Segunda Lei de Mendel",
    "Interação Gênica e Epistasia",
    "Herança poligênica",
    "Ligação Gênica e Crossing-Over",
    "Herança ligada ao sexo e doenças relacionadas ao cromossomo X",
    "Genética de Populações",
    "Mutações Gênicas",
    "Mutações Cromossômicas",
    "Engenharia Genética: DNA Recombinante, Técnicas de PCR e Transgênicos",
    "Engenharia Genética: clonagem e células tronco",
    "Embriologia: etapas do desenvolvimento embrionário",
    "Embriologia: anexos embrionários",
    "Tecido Epitelial",
    "Tecido Conjuntivo",
    "Tecido Muscular",
    "Tecido Nervoso",
    "Anatomia e Fisiologia do Sistema Digestório Humano",
    "Anatomia e Fisiologia do Sistema Respiratório Humano",
    "Anatomia e Fisiologia do Sistema Circulatório Humano",
    "Sistema Imunológico e Imunodeficiências",
    "Anticorpos, Vacinas e Soros",
    "Anatomia e Fisiologia do Sistema Excretor",
    "Anatomia e Fisiologia do Sistema Nervoso",
    "Sistema Endócrino",
    "Anatomia e Fisiologia do Sistema Reprodutor",
    "Ciclo menstrual e Anticoncepção",
    "Taxonomia e Filogenia",
    "Vírus e Viroses",
    "Bactérias e Bacterioses",
    "Fungos",
    "Algas",
    "Protozoários: características",
    "Protozooses: Doença de Chagas, amebíase e giardíase",
    "Protozooses: Malária, leishmaniose e toxoplasmose",
    "Poríferos e Cnidários",
    "Platelmintos: características gerais",
    "Nematódeos: características gerais",
    "Verminoses por Platelmintos: Teníase, Cisticercose e Esquistossomose",
    "Verminoses por Nematódeos: Ascaridíase e Ancilostomíase, Enterobíase e Filariose",
    "Anelídeos: Características gerais",
    "Artrópodes: características gerais",
    "Insetos",
    "Crustáceos, Miriápodes e Aracnídeos",
    "Moluscos: Características Gerais",
    "Equinodermos: Características Gerais",
    "Cordados basais: Características Gerais",
    "Peixes",
    "Anfíbios",
    "Répteis",
    "Aves",
    "Mamíferos",
    "Briófitas: aspectos gerais, evolução e reprodução",
    "Pteridófitas: aspectos gerais, evolução e reprodução",
    "Gimnospermas: aspectos gerais, evolução e reprodução",
    "Angiospermas: aspectos gerais, evolução e reprodução",
    "Angiospermas: flor, semente e fruto.",
    "Histologia vegetal: tecidos meristemáticos e adultos.",
    "Transpiração Vegetal",
    "Condução das seivas Bruta e Elaborada",
    "Hormônios Vegetais",
    "Movimentos vegetais",
    "Fotoperiodismo"
  ],
  "Educação física": [
    "Padrão estético contemporâneo",
    "Influência da mídia no corpo",
    "Exercício Físico e Saúde",
    "Condicionamento e Esforço Físico",
    "Autoestima e cirurgias plásticas",
    "Doenças mentais no século XXI",
    "Obesidade",
    "Vivência Crítica e Emancipada do Lazer",
    "Práticas Corporais e Autonomia",
    "O Corpo Como Expressão Artística e Cultural",
    "Danças Folclóricas",
    "Danças Africanas",
    "O papel Social do Funk no Brasil",
    "O Rap como Manifestação Cultural",
    "O samba",
    "Capoeira",
    "O papel social do Esporte",
    "Atletismo",
    "Basquetebol",
    "Futebol/Futsal",
    "Ginástica artística",
    "Handebol",
    "Voleibol",
    "Olimpíadas e Paraolimpíadas",
    "Esportes Adaptados",
    "Lutas",
    "Jogos",
    "Brincadeiras"
  ],
  "Filosofia": [
    "Surgimento da Filosofia: O Contexto Sociopolítico na Grécia Antiga",
    "Conceitos: Mito, Senso Comum, Filosofia e Ciência",
    "Pré-Socráticos: Tales de Mileto, Anaximandro e Anaxímenes",
    "Pré-Socráticos: Heráclito e Parmênides",
    "Sofistas",
    "Socráticos: Método Dialético, Maiêutica e Ironia em Sócrates",
    "Socráticos: A República e o Mito da Caverna em Platão",
    "Socráticos: Ética e Eudaimonia em Aristóteles",
    "Socráticos: Metafísica e Lógica em Aristóteles",
    "Inatismo, Empirismo e a “Escola de Atenas” de Rafael Sanzio",
    "Epistemologia, Gnosiologia e Ontologia",
    "Método Indutivo e Método Dedutivo",
    "Pós-Socráticos: Epicurismo, Estoicismo, Cinismo e Ceticismo",
    "Filosofia Medieval: Santo Agostinho e Patrística",
    "Filosofia Medieval: São Tomás de Aquino e Escolástica",
    "Maquiavel: O Príncipe",
    "Montaigne: Humanismo e o Gênero Ensaio",
    "Thomas Hobbes: Leviathan",
    "Jean-Jacques Rousseau: O Contrato Social",
    "René Descartes: Racionalismo e o Método Científico",
    "René Descartes: Dúvida Metódica e Hiberbólica",
    "John Locke: Empirismo e a Tabula Rasa",
    "John Locke: Liberalismo e Contratualismo",
    "Montesquieu: O Espírito das Leis e a Separação dos Três Poderes",
    "Immanuel Kant: Moral, Ética e Estética",
    "Immanuel Kant: Emancipação e Civilidade",
    "Jeremy Bentham: Utilitarismo e o Panóptico",
    "Schopenhauer: Felicidade e Sofrimento",
    "Nietzsche: O Eterno Retorno, a Genealogia da Moral e o Super-homem",
    "Existencialismo: Sartre e Heidegger",
    "Sigmund Freud: Inconsciente e Psicanálise",
    "Edmund Husserl: Fenomenologia",
    "Estruturalismo: Wilhelm Wundt, Ferdinand Saussure e Claude Lévi-Strauss",
    "Hannah Arendt: Banalização do Mal",
    "Karl Popper: Falseabilidade e Neopositivismo",
    "Noam Chomsky: Gramática Gerativa",
    "Revolução genética e Bioética"
  ],
  "Física": [
    "Grandezas Físicas, Notação Padrão e Unidades de medida",
    "Conceitos Básicos e definições da Cinemática",
    "Velocidade escalar média",
    "MRU: Movimento Retilíneo e Uniforme",
    "Aceleração escalar",
    "MUV: Movimento uniformemente variado",
    "Queda Livre",
    "Lançamento Vertical",
    "Componentes de operações e decomposição de vetores",
    "Vetores no deslocamento, na velocidade e na aceleração",
    "Lançamento Horizontal",
    "Lançamento Oblíquo",
    "MCU: Movimento Circular e Uniforme",
    "Movimentos concêntricos e Transmissão de MCU",
    "Introdução à Dinâmica: conceitos e tipos de forças",
    "Leis de Newton",
    "Força Peso, Normal e Força de Tração",
    "Força Elástica",
    "Força de Atrito Estático e Dinâmico",
    "Plano Inclinado",
    "Forças da Dinâmica em Elevadores",
    "Dinâmica no MCU",
    "Trabalho de uma Força",
    "Equilíbrio de corpos extensos",
    "Energia Cinética",
    "Energia Potencial Gravitacional",
    "Energia Potencial Elástica",
    "Energia Mecânica, conservação e dissipação da Energia",
    "Potência e Rendimento",
    "Quantidade de Movimento",
    "Impulso: Teorema do Impulso",
    "Colisões unidimensionais e bidimensionais",
    "Conceitos de Densidade e Pressão",
    "Conceitos fundamentais da Hidrostática",
    "Empuxo",
    "Termometria: Escalas termométricas",
    "Dilatação Térmica",
    "Calorimetria: Calor sensível e Calor Latente",
    "Trocas de calor entre corpos",
    "Fenômenos físicos de propagação do calor",
    "1ª Lei da Termodinâmica e transformações termodinâmicas",
    "2ª Lei da Termodinâmica",
    "Fundamentos e Princípios da Óptica Geométrica",
    "Espelhos planos",
    "Espelhos Esféricos (30%) Leis da Refração (50%) Dioptro Plano",
    "Lentes Esféricas 1",
    "Lentes Esféricas 2",
    "Óptica da Visão",
    "Conceitos e Fundamentos da Ondulatória",
    "Reflexão e Refração da onda",
    "Difração, Polarização e Ressonância",
    "Interferência, Batimento e Ondas Estacionárias",
    "Ondas Sonoras: Conceitos e Fundamentos",
    "Cordas sonoras",
    "Tubos Sonoros",
    "Efeito Doppler",
    "Carga Elétrica",
    "Corrente elétrica e Tensão",
    "Potência Elétrica",
    "1ª Lei de Ohm: Resistores",
    "2ª Lei de Ohm",
    "Resistores em série e em paralelo",
    "Geradores e Receptores Elétricos",
    "Circuitos elétricos com Geradores, Resistores e Receptores",
    "Voltímetro e Amperímetro",
    "Ponte de Wheatstone",
    "Leis de Kirchhoff",
    "Resolução e Revisão: Circuitos Elétricos completos",
    "Força elétrica e Lei de Coulomb",
    "Campo elétrico e Linhas de campo",
    "Potencial Elétrico",
    "Campo Elétrico Uniforme",
    "Processos de Eletrização",
    "Capacitores",
    "Magnetismo e Campo Magnético",
    "Campo magnético gerado pela corrente elétrica - Regra da mão direita",
    "Força Magnética - Regra da mão esquerda",
    "Movimento de cargas no campo magnético",
    "Indução Eletromagnética",
    "Leis de Kepler",
    "Lei da Gravitação Universal",
    "Campo Gravitacional"
  ],
  "Geografia": [
    "Demografia, Conceitos Demográficos, Indicadores Demográficos e IBGE",
    "Teorias Demográficas, Transição Demográfica e Estrutura da População",
    "Migração: Fatores Migratórios e Tipos de Migração",
    "Fluxos Migratórios Principais do Brasil",
    "Fluxos Migratórios Principais do Mundo, Refugiados e Declaração de Salamanca",
    "Urbanização Brasileira, Formação de Metrópoles e Metrópoles Brasileiras",
    "Transporte no Brasil e Mobilidade Urbana",
    "Problemas Sociais e Ambientais Urbanos",
    "Setores da Economia e Diferenciação entre Setor Terciário, Terceiro Setor e Terceirização",
    "Revoluções Industriais",
    "Regiões Industrializadas do Mundo",
    "Industrialização no Brasil: A evolução da Atividade Industrial e Regiões Industrializadas",
    "Modelos de Produção Industrial: Taylorismo, Fordismo, Toyotismo e Volvismo",
    "Tipos de Indústrias e Commodities",
    "Revolução Verde",
    "Sistemas Agrícolas, Agronegócio e Agropecuária no Brasil",
    "Modernização Agrícola e Complexos Agroindustriais",
    "Urbanização do Campo e Êxodo Urbano",
    "Cinturões Verdes, Agricultura Irrigada e Agroecologia",
    "Alimentos Transgênicos, Orgânicos, Hidropônicos e Híbridos",
    "Estrutura Fundiária, Reforma Agrária e os Conflitos no Campo",
    "Questão Indígena, Demarcação de Terras, Quilombolas e Frentes pioneiras",
    "Devastação da Amazônia, Chico Mendes e Tragédia de Mariana",
    "Preservação Meio Ambiente, ECO-92, Protocolo Kyoto, Tratado Paris e COP26",
    "Ação Antrópica e Impacto Ambiental: Poluição dos Solos, Ar e Água",
    "Milton Santos: Paisagem e Espaço Geográfico",
    "Sustentabilidade, Formas de Tratamento de Lixo e 3Rs",
    "Crise de Superprodução e Obsolescência Programada",
    "Divisão Internacional do Trabalho e Fases do Capitalismo",
    "Desigualdade Mundial, PIB, IDH e Índice Gini",
    "Velha Ordem Mundial, Nova Ordem Mundial e “Nova Guerra Fria”",
    "Política e Economia dos EUA",
    "Política e Economia da União Europeia e o Brexit",
    "Política e Economia da China",
    "Economia do Japão, Tigres Asiáticos e Novos Tigres Asiáticos",
    "Substituição de Importação, Plataforma de Exportação, Balança Comercial e Logística",
    "Blocos Econômicos, ONU e Outros Organismos Internacionais",
    "Tecnologia, Telecomunicações, Internet e Armamentismo Contemporâneo",
    "Regiões Separatistas e Terrorismo no Mundo Atual",
    "Conceitos: Território, Estado, Nação, País, Governo, Povo e Etnia",
    "Sistemas de Governo e Formas de Governo",
    "Tensões Geopolíticas Atuais: AMÉRICA",
    "Tensões Geopolíticas Atuais: EUROPA",
    "Tensões Geopolíticas Atuais: ÁSIA",
    "Tensões Geopolíticas Atuais: ÁFRICA",
    "Tensões Geopolíticas Atuais: ORIENTE MÉDIO",
    "Cartografia: Orientação, Localização e Fusos Horários",
    "Cartografia: Convenções, Projeções e Escala",
    "Sensoriamento Remoto: Satélites, GPS e Triangulação de Antena",
    "Estrutura Interna da Terra, Teoria da Deriva Continental e Eras Geológicas",
    "Dinâmica do Relevo: Agentes Modeladores do Relevo Internos e Externos",
    "Tipos de Relevo e Formas de Relevo",
    "Relevo Brasileiro: Classificação de Aroldo de Azevedo e de Aziz Ab’Saber",
    "Relevo Brasileiro: Classificação de Jurandyr Ross",
    "O Quatro Brasis de Milton Santos",
    "Estruturas Geológicas do Brasil e do Mundo",
    "Principais Recursos Minerais no Brasil",
    "Formação das Rochas e Tipos de Rochas",
    "Formação dos Solos e Tipos de Solos",
    "Elementos Climáticos e Fatores Climáticos",
    "Meteorologia Básica: Movimento dos Astros, Planetas, Fases da Lua e Eclipse",
    "Fenômenos Climáticos: Ciclones, Brisa Marinha, Maré e Onda",
    "Mudanças Climáticas: Aquecimento Global, El Niño e La Niña",
    "Principais Climas do Mundo e seus Climogramas",
    "Climas Brasileiros e seus Climogramas",
    "Massas de Ar no Brasil e Rios Voadores",
    "Dinâmica dos Ventos e Zonas Térmicas da Terra",
    "Tipos de Ventos, Tipos de Chuvas e Tipos de Nuvens",
    "Principais Biomas do Mundo",
    "Biomas Brasileiros, Domínios Morfoclimáticos e Hotspots",
    "Bacias Hidrográficas, Principais Rios, Hidrelétricas e Portos do Brasil",
    "Distribuição de Água no Mundo",
    "Pegada Hídrica, Água Virtual e Ciclo Hidrológico",
    "Fontes de Energia Renováveis e Não Renováveis",
    "Distribuição de Petróleo pelo Mundo e pelo Brasil",
    "Distribuição da Geração e do Consumo de Energia no Brasil",
    "Regionalismo: Aspectos Físicos, Populacionais e Econômicos do NORDESTE",
    "Regionalismo: Aspectos Físicos, Populacionais e Econômicos do NORTE",
    "Regionalismo: Aspectos Físicos, Populacionais e Econômicos do CENTRO-OESTE",
    "Regionalismo: Aspectos Físicos, Populacionais e Econômicos do SUDESTE",
    "Regionalismo: Aspectos Físicos, Populacionais e Econômicos do SUL"
  ],
  "História": [
    "“Pré-História” e Desenvolvimento Cultural do Homo Sapiens",
    "Civilizações Hidráulicas da Antiguidade Oriental: Mesopotâmia e Egito",
    "Outros Povos da Antiguidade: Persas, Hebreus e Fenícios",
    "Grécia Antiga: Cultura Grega e Olimpíadas",
    "Grécia Antiga: Estrutura Social e Política de Atenas e Esparta",
    "Grécia Antiga: Os Primeiros Legisladores Atenienses",
    "Democracia na Grécia Antiga e Evolução da Democracia",
    "Período Helenístico: Cultura e Arte",
    "Roma Antiga: Monarquia, República e Império",
    "Heranças do Império Romano para o Mundo Atual: Direito, Latim, Arquitetura e Cristianismo",
    "Queda do Império Romano e Império Bizantino",
    "Bárbaros e Império Carolíngio",
    "Feudalismo: Sociedade, Cultura e o Poder da Igreja Católica",
    "Cruzadas e Império Islâmico",
    "Peste Negra, Guerra dos 100 anos e Declínio Feudal",
    "Renascimento Cultural e Revolução Científica",
    "Transição para o Capitalismo e Formação dos Estados Nacionais",
    "Absolutismo, Mercantilismo e Expansão Marítima",
    "América Espanhola e as Civilizações Nativas: Maias, Astecas e Incas",
    "Reforma Protestante e Contrarreforma Católica",
    "Iluminismo e Liberalismo",
    "Revoluções Inglesas",
    "Revolução Industrial",
    "Independência dos EUA e a Guerra de Secessão",
    "Revolução Francesa e Período Napoleônico",
    "Independência da América Espanhola",
    "Congresso de Viena e Primavera dos Povos",
    "Antíteses do Capitalismo Industrial: Ludismo, Socialismo Utópico e Socialismo Científico",
    "Unificações Italiana e Alemã",
    "Imperialismo e Paz Armada",
    "Primeira Guerra Mundial e Tratado de Versalhes",
    "Revolução Russa: Do Czarismo ao Stalinismo",
    "Crise de 29",
    "Nacionalismo, Fascismo, Nazismo e Franquismo",
    "Guerra Civil Espanhola",
    "Segunda Guerra Mundial e Ascensão do Comunismo",
    "Guerra Fria e Avanços Tecnológicos",
    "Independência da Indochina e Guerra do Vietnã",
    "Declínio da Guerra Fria: Perestroika e Glasnost",
    "Descolonização da África e da Ásia",
    "Formação de Israel e Estado Palestino",
    "Conflitos do Oriente Médio e Primavera Árabe",
    "História da China: De Mao Tsé-Tung a Potência Global",
    "Revolução de Avis e a Formação de Portugal",
    "Pioneirismo Marítimo Português e o “Descobrimento” do Brasil",
    "Povos Ameríndios no Brasil: Cultura e Identidade dos Povos Indígenas",
    "Brasil Pré-Colonial: Escambo, Feitorias e Pau-Brasil",
    "Capitanias Hereditárias e o Governo-Geral",
    "Os Jesuítas no Brasil",
    "Ciclo da Cana-de-Açúcar e a Economia Açucareira",
    "Escravidão, Reinos Africanos, Tráfico Negreiro e Diáspora Africana",
    "Brasil Colônia: Drogas do Sertão e Atividades Econômicas Complementares",
    "Os Quilombos e a Resistência Negra",
    "União Ibérica e as Invasões Estrangeiras",
    "Brasil Colônia: Expansão Territorial Brasileira",
    "Entradas, Bandeiras e Monções",
    "Ciclo do Ouro e o Período Pombalino",
    "Revoltas Nativistas: Data, Local, Duração, Motivo, Líderes e Resposta do Governo",
    "Revoltas Separatistas: Data, Local, Duração, Motivo, Líderes e Resposta do Governo",
    "A chegada da Família Real e o Período Joanino",
    "A Evolução da Relação Brasil-Inglaterra e Tratados",
    "Revolução Pernambucana",
    "Independência do Brasil",
    "Primeiro Reinado: Sociedade, Política e Economia",
    "Período Regencial e as Revoltas Regenciais",
    "Segundo Reinado: Sociedade, Economia e Política Externa",
    "Guerra do Paraguai, Crise do Império e Governo Provisório",
    "República da Espada: Sociedade, Política e Economia",
    "República Oligárquica: Sociedade, Política e Economia",
    "Ciclo da Borracha e a “Belle Époque Amazônica”",
    "Revoltas da República Velha: Canudos, Contestado, Vacina e Chibata",
    "O Cangaço e o Banditismo Social",
    "República Oligárquica: Coluna Prestes e Crise da República Velha",
    "Era Vargas: Sociedade, Política e Economia",
    "República Populista: Dutra e Vargas",
    "República Populista: Café Filho e JK",
    "República Populista: Jânio Quadros e João Goulart",
    "Ditadura Militar: Golpe e Cronologia dos Presidentes",
    "Ditadura Militar: Atos Institucionais, Censura e Tortura",
    "Ditadura Militar: Economia e Obras Faraônicas",
    "Ditadura Militar: Manifestações Culturais e Exílio",
    "Exploração de Ouro da Serra Pelada",
    "A Evolução das Constituições do Brasil",
    "Nova República: Redemocratização, Hiperinflação e os Governo Sarney e Collor",
    "Nova República: Estabilização Econômica e o Plano Real dos Governos Itamar Franco e FHC",
    "Nova República: Contradições dos Governos Lula e Dilma, BRICS e Governo Temer",
    "Nova República: Bolsonaro, Degradação dos Indicadores Sociais e Devastação da Amazônia"
  ],
  "Língua estrangeira (espanhol)": [
    "Estrategia de lectura en españo",
    "Interpretación de texto",
    "Introducción a la cultura hispano-americana",
    "Los verbos",
    "El presente del indicativo",
    "Leguaje coloquial y familiar",
    "las prendas de vestir",
    "Los colores",
    "los contrários",
    "Sitios turísticos y comerciales",
    "Heterosemánticos",
    "Las profesiones",
    "El cuerpo humano",
    "La família",
    "Los artículos y el género",
    "Los advérbios",
    "los materiales",
    "pretéritos del indicativo",
    "apócope",
    "Las finanzas",
    "Las preposiciones",
    "Los animales",
    "Los números",
    "Las horas",
    "Las conjunciones",
    "Los fenómenos naturales",
    "Muy x mucho",
    "Las medicinas",
    "Tilde diacrítica",
    "Sustantivos abstractos – Verbos gustar, parecer, encantar",
    "Partes y objetos de la casa",
    "Los alimentos",
    "Los pronombres",
    "El Futuro Imperfecto y el condicional",
    "El Subjuntivo",
    "Expresiones lingüísticas",
    "Textos Periodisticos",
    "Historietas y comics",
    "Análisis de Fotos y Pinturas",
    "Falsos Amigos em español"
  ],
  "Língua estrangeira (inglês)": [
    "Basic Review",
    "Reading Technique",
    "Nouns",
    "Genitive Case",
    "Articles",
    "Pronouns",
    "Interrogatives Adverbs",
    "Simple Present Tense",
    "Simple Past Tense",
    "Present Continuous Tense",
    "Past Continuous Tense",
    "Future Tense",
    "Present Perfect Tense",
    "Past Perfect Tense",
    "Modal Verbs",
    "Relative Pronouns",
    "Quantitative Adjectives",
    "Indefinite Pronouns",
    "Degrees of Comparison",
    "Tag Questions",
    "Adverbs",
    "Conjunctions and connectors",
    "The Passive Voice",
    "Suffixes and prefixes",
    "If Clauses",
    "Prepositions",
    "Reported Speech",
    "Linking words",
    "Phrasal Verbs",
    "False Cognates",
    "Causative Verbs",
    "Use of Gerund and Infinitive",
    "Special Difficulties",
    "Quantifiers",
    "Adjectives",
    "Journalistic texts",
    "Comic strips and cartoon",
    "Technical text",
    "Advertisement"
  ],
  "Língua portuguesa": [
    "Compreensão e Interpretação de texto",
    "Técnicas de leitura",
    "Estrutura e formação de palavras",
    "Funções da linguagem",
    "Elementos da Comunicação",
    "Gêneros textuais",
    "Tipologia textual",
    "Intertextualidade e Paráfrase",
    "Figuras de linguagem",
    "Efeitos de Sentido",
    "Semântica",
    "Linguagem, Língua e Fala",
    "Variação Linguística",
    "Conjunção e Palavras denotativas: Conceito, classificações e aplicações",
    "Vocabulário aplicado à prova"
  ],
  "Literatura": [
    "Introdução à Literatura",
    "Gêneros literários: Épico, lírico, dramática, ensaístico",
    "Elementos da poesia",
    "Elementos da prosa",
    "Trovadorismo",
    "Humanismo",
    "Classicismo",
    "Quinhentismo",
    "Barroco: origem, contexto histórico e características",
    "Barroco: Gregório de Matos Guerra e Pe. Antônio Vieira",
    "Arcadismo: origem, contexto histórico e características",
    "Arcadismo: Tomás Antônio Gonzaga e Cláudio Manuel da Costa",
    "Romantismo: origem, contexto histórico e características",
    "1a Geração Romântica",
    "2a Geração Romântica",
    "3a Geração Romântica",
    "José de Alencar e Manuel Antônio de Almeida",
    "Realismo",
    "Eça de Queirós e Machado de Assis",
    "Naturalismo",
    "Parnasianismo",
    "Simbolismo",
    "Pré-Modernismo",
    "Euclides da Cunha e Lima Barreto",
    "Monteiro Lobato e Augusto dos Anjos",
    "Vanguardas Europeias",
    "Fernando Pessoa",
    "Semana de Arte Moderna",
    "1a Fase Modernista",
    "Mário de Andrade, Oswald de Andrade e Manuel Bandeira",
    "2a Fase Modernista",
    "Graciliano Ramos, Carlos Drummond de Andrade e Vinicius de Moraes",
    "3a Fase Modernista",
    "Guimarães Rosa, Clarice Lispector e João Cabral de Melo Neto",
    "Pós-modernismo",
    "Concretismo e Neoconcretismo",
    "Tropicalismo",
    "Poesia Marginal",
    "Poesia-Práxis",
    "Poema processo",
    "Haicai",
    "Autores Contemporâneos",
    "Literatura de cordel",
    "Prosa contemporânea",
    "Análise de Obras"
  ],
  "Matemática": [
    "Adição e Subtração",
    "Multiplicação e Divisão",
    "Notações Matemáticas e Glossário Básico",
    "Operações com Números Reais",
    "Divisibilidade, MMC e MDC",
    "Conjuntos Numéricos",
    "Frações",
    "Propriedades Distributivas",
    "Potenciação",
    "Radiciação",
    "Produtos Notáveis",
    "Fatoração",
    "Sistemas Métricos e Base Decimal",
    "Lógica Matemática",
    "Equação de Primeiro Grau",
    "Equação de Segundo Grau",
    "Equação Exponencial",
    "Porcentagem",
    "Aumentos e Descontos Percentuais",
    "Juros Simples e Compostos",
    "Razão, Proporção e Escala Cartográfica",
    "Regra de Três Simples e Composta",
    "Interpretação de Gráficos e Tabelas",
    "Estatística: Média, Mediana e Moda",
    "Frequência Absoluta e Relativa",
    "Variância e Desvio Padrão",
    "Introdução a Funções e Domínio de uma função real",
    "Teoria dos Conjuntos",
    "Função Constante e Função Afim",
    "Introdução à Função Quadrática",
    "Função Quadrática: Pontos Extremos",
    "Função Composta e Inversa",
    "Módulo e Função Modular",
    "Função Exponencial",
    "Inequações do Primeiro e Segundo Grau",
    "Inequações: Produto e Quociente",
    "Inequação Exponencial",
    "Logaritmos: Definição e Existência",
    "Logaritmos: Propriedades",
    "Equações Logarítmicas",
    "Funções Logarítmicas",
    "Inequação Logarítmica",
    "Polinômios Fundamentos",
    "Equações Polinomiais",
    "Progressão Aritmética: Definição e Termo Geral",
    "Progressão Aritmética: Soma dos Termos",
    "Progressão Geométrica: Definição e Termo Geral",
    "Progressão Geométrica: Soma dos Termos e da Convergente Infinita",
    "Fatorial",
    "Princípio Fundamental da Contagem",
    "Permutações",
    "Arranjos e Combinações",
    "Números Binomiais",
    "Probabilidade: Definição",
    "Probabilidade: Aplicações práticas",
    "Probabilidade condicional",
    "Matriz: Conceito e Operações Básicas",
    "Matriz: produto",
    "Definição e Cálculo: Determinantes",
    "Método de Escalonamento",
    "Sistemas Lineares: Discussão",
    "Sistema Linear Homogêneo",
    "Noções Primitivas de Geometria Plana",
    "Triângulos",
    "Pontos Notáveis de um Triângulo",
    "Semelhança de Triângulos e Teorema de Tales",
    "Quadriláteros",
    "Polígonos",
    "Triângulo Retângulo",
    "Lei dos Senos e Cossenos",
    "Áreas de Polígonos",
    "Círculos",
    "Ângulos na Circunferência",
    "Poliedros",
    "Prismas",
    "Pirâmides",
    "Cilindros",
    "Cones",
    "Esferas",
    "Troncos",
    "Inscrição de Sólidos",
    "Sistema Cartesiano e Ponto",
    "Estudo Analítico da Reta",
    "Circunferência",
    "Posições Relativas à Circunferência",
    "Cônicas",
    "Trigonometria no Triângulo Retângulo",
    "Arcos e Ciclo Trigonométrico",
    "Função Seno e Cosseno",
    "Função Tangente e Cotangente",
    "Equações e Inequações Trigonométricas"
  ],
  "Redação": [
    "O Texto Dissertativo-argumentativo: Características e Particularidades",
    "O Texto Dissertativo-argumentativo: Estrutura",
    "Concisão no Parágrafo e Progressão Textual",
    "O Tema na Redação do ENEM: Particularidades, Interpretação e Delimitação",
    "Projeto de Texto",
    "Marca de Autoria",
    "Fuga e Tangência",
    "Aspectos Formais Relevantes",
    "Gramática Aplicada à Redação: Concordância verbal e nominal",
    "Gramática Aplicada à Redação: Regência verbal e nominal",
    "Gramática Aplicada à Redação: Acentuação",
    "Gramática Aplicada à Redação: Pontuação",
    "Gramática Aplicada à Redação: Crase",
    "Gramática Aplicada à Redação: Ortografia",
    "Vícios de linguagem: Conceito, Classificação e Tipos",
    "Título",
    "Introdução: Função e Microestrutura",
    "Tese",
    "Desenvolvimento: Função e Estrutura",
    "Métodos de raciocínio: indução e dedução",
    "Métodos de raciocínio: dialética e falhas na argumentação",
    "Argumentação e estratégias argumentativas",
    "Repertório Sociocultural: Conceito, aplicação e classificação",
    "Conclusão: Função e Microestrutura",
    "Proposta de intervenção: Agente",
    "Proposta de intervenção: Ação",
    "Proposta de intervenção: Meio/Modo",
    "Proposta de intervenção: Detalhamento",
    "Proposta de intervenção: Finalidade",
    "Redação ENEM: Competência 1",
    "Redação ENEM: Competência 2",
    "Redação ENEM: Competência 3",
    "Redação ENEM: Competência 4",
    "Redação ENEM: Competência 5",
    "Leitura e aproveitamento da coletânea/ texto de apoio",
    "Coesão Textual: Conceito, Classificação e Tipos",
    "Coerência Textual",
    "Análise de redações Exemplares: 1",
    "Análise de redações Exemplares: 2"
  ],
  "Química": [
    "Propriedades da matéria",
    "Substâncias químicas e suas transformações",
    "Substâncias puras, Misturas homogêneas e Misturas Heterogêneas",
    "Separação de Misturas",
    "Modelos Atômicos: Dalton e Thomson",
    "Modelos Atômicos: Rutherford",
    "Modelos Atômicos: Bohr",
    "Atomística: Composição e Propriedades Atômicas e Interatômicas",
    "Distribuição Eletrônica",
    "Tabela Periódica: Classificação periódica e Propriedades Periódicas",
    "Ligação Iônica",
    "Ligação Covalente e Dativa",
    "Ligação Metálica",
    "Geometria Molecular",
    "Polaridade das ligações químicas",
    "Polaridade das moléculas",
    "Interações Intermoleculares",
    "Princípio da Solubilidade",
    "Massa atômica e Massa molecular",
    "Definição de Mol e Massa molar",
    "Cálculos de Mol",
    "Leis ponderais",
    "Fórmula percentual, mínima e molecular",
    "Balanceamento de equações químicas",
    "Cálculo Estequiométrico: casos simples",
    "Cálculo Estequiométrico: reagente em excesso e limitante",
    "Cálculo Estequiométrico: pureza e rendimento",
    "Soluções e solubilidade: Conceitos e Propriedades",
    "Concentração de soluções 1",
    "Concentração de soluções 2",
    "Diluição de soluções",
    "Mistura de soluções",
    "Titulação",
    "Comportamento físico dos gases",
    "Transformações Isotérmicas, Isobáricas e Isovolumétricas",
    "Equação geral dos gases",
    "Lei de Avogadro",
    "Equação de Clapeyron",
    "Mistura gasosa e Densidade dos gases",
    "Termoquímica: conceitos e Entalpia",
    "Cálculo da variação de Entalpia",
    "Entalpia de combustão e poder calorífico",
    "Lei de Hess",
    "Número de oxidação Nox",
    "Reações de oxirredução",
    "Pilhas",
    "Eletrólise ígnea",
    "Eletrólise Aquosa e galvanização",
    "Eletrólise quantitativa",
    "Tonoscopia, Ebulioscopia, Crioscopia e Osmocopia",
    "Introdução à Química Orgânica e Cadeias Carbônicas",
    "Hidrocarbonetos: nomenclatura e classificação",
    "Cadeias Aromáticas",
    "Funções Orgânicas: Oxigenados",
    "Funções Orgânicas: Nitrogenados e Haletos Orgânicos",
    "Isomeria Plana",
    "Isomeria Geométrica",
    "Isomeria Óptica",
    "Propriedades Físicas dos Compostos Orgânicos",
    "Ácidos e Bases Orgânicos",
    "Reações Orgânicas: Adição",
    "Reações Orgânicas: Substituição",
    "Reações orgânicas: Eliminação e Esterificação",
    "Reações Orgânicas: Oxidação",
    "Bioquímica: lipídeos, proteínas e carboidratos",
    "Polímeros",
    "Petróleo",
    "Radioatividade: definição, conceitos",
    "Emissões radioativas",
    "Decaimento Radioativo, Fusão e Fissão nuclear",
    "Química Ambiental e Poluição Atmosférica",
    "Ácidos: definição, nomenclatura e ionização",
    "Bases: definição, nomenclatura e dissociação",
    "Reações de Neutralização: ácido + base",
    "Sais: Definição, nomenclatura e classificação",
    "Óxidos: Definição, nomenclatura e classificação",
    "Reações Inorgânicas: adição e decomposição",
    "Reações Inorgânicas: simples-troca ou deslocamento",
    "Reações inorgânicas: dupla-troca",
    "Introdução à Cinética Química",
    "Condições de ocorrência das reações - Teoria das colisões e Complexo Ativado",
    "Fatores que influenciam a velocidade da reação química e catalisadores",
    "Equilíbrio Químico: definição e conceitos",
    "Constante de Equilíbrio - Kc",
    "Deslocamento do Equilíbrio Químico",
    "pH",
    "Hidrólise Salina"
  ],
  "Sociologia": [
    "Surgimento da Sociologia: Contexto Histórico-Social",
    "Augusto Comte: Positivismo e a Lei dos Três Estados",
    "Émile Durkheim: Sociologia como Ciência e Fatos Sociais",
    "Émile Durkheim: Instituições Sociais, Solidariedade e Suicídio",
    "Max Weber: Ética Protestante e o Espírito Do Capitalismo",
    "Max Weber: Poder, Dominação Legítima e Ação Social",
    "Etnocentrismo e Antropologia Social",
    "Evolucionismo Cultural e Relativismo Social",
    "Friedrich Hegel: Método Dialético",
    "Karl Marx: Materialismo Histórico, Alienação e Mais-Valia",
    "Karl Marx: Luta de Classes e Manifesto Comunista",
    "Antônio Gramsci: Hegemonia Cultural",
    "Declaração dos Direitos do Homem e do Cidadão, 1789",
    "Declaração Universal dos Direitos Humanos, 1948",
    "Constituição de 1988: Constituição Cidadã, 1988",
    "Marshall: Cidadania e Classe Social",
    "Teoria do Trabalho: Durkheim, Marx e Weber",
    "Novas Relações de Trabalho, Precarização do Trabalho e Escravidão Moderna",
    "Segregação Socioespacial Urbana, Atitude Blasé e Gentrificação",
    "Função Social do Espaço Público e Gestão Participativa",
    "Patrimônio Cultural Material e Imaterial Brasileiro e Bens Culturais",
    "Apropriação Cultural e Ressignificação Cultural",
    "Racismo, Ações Afirmativas e Resistência Cultural",
    "Sérgio Buarque de Holanda: Homem Cordial",
    "Gilberto Freyre e Florestan Fernandes: Relações Raciais no Brasil",
    "Marginalização Social e Carolina Maria de Jesus: Quarto de Despejo",
    "Segregação Racial nos EUA e Apartheid na África do Sul",
    "Desobediência Civil: David Henry Thoreau e Mahatma Gandhi",
    "Desigualdade Social, Estratificação Social e Mobilidade Social",
    "Dominação, Manutenção do Status Quo e o Mito da Meritocracia",
    "Minorias Sociais e Luta Política",
    "Sociedade em Rede, Sociedade Informacional e Mídias Sociais",
    "Opressão contra a Mulher, Luta por Igualdade de Direitos e Movimento Sufragista",
    "Diversidade Cultural, Estereótipos de Gênero e Invisibilidade Social",
    "Identidade Cultural e Globalização",
    "Indústria Cultural: Escola de Frankfurt, Adorno e Horkheimer",
    "Habermas: Teoria da Ação Comunicativa",
    "Cultura de Massa e Sociedade do Espetáculo",
    "Consumismo, Individualismo, Tribalismo, Sujeito Pós-Moderno",
    "Michel Foucault: Poder e Controle Social",
    "Zygmunt Bauman: Modernidade Líquida",
    "Gilles Lipovetsky: Hipermodernidade",
    "Paulo Freire: Pedagogia do Oprimido",
    "Equidade e John Rawls: Teoria da Justiça"
  ],
  "Tecnologia da informação e comunicação": [
    "Função e Impacto das Novas Mídias",
    "Gêneros Digitais",
    "Cibercultura",
    "Redes Sociais e Relações na Sociedade Atual",
    "Metaverso",
    "Meios de Comunicação e a Indústria Cultural",
    "Internet, as Organizações Políticas e a Censura",
    "Marco Civil da Internet",
    "Ética na internet",
    "Privacidade na Internet",
    "Inclusão digital e acesso democrático",
    "Letramento digital",
    "Criptomoedas e Economia digital",
    "Inteligência artificial e internet das coisas",
    "Marketing tradicional x Marketing digital"
  ]
};
